# Generated by Django 4.0.3 on 2022-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='fecha',
            field=models.CharField(default='Sin fecha', max_length=100),
            preserve_default=False,
        ),
    ]
